version: '3'
services:
  client:
    container_name: jonay2000-homepage-client
    image: jonay2000/collabdraw:latest
    networks:
      - web
    labels:
      - traefik.protocol=http 
      - traefik.frontend.rule=Host:drawing.jonay2000.nl,www.drawing.jonay2000.nl,jonay2000.nl,www.jonay2000.nl
      - traefik.frontend.redirect.regex=http(s*)://www.(.+)
      - traefik.frontend.redirect.replacement=http$$1://$$2
      - traefik.frontend.redirect.permanent=true
      - traefik.frontend.port=80
    restart: unless-stopped
  server:
    container_name: jonay2000-homepage-server
    image: jonay2000/collabdraw-server:latest
    env_file: ./settings.env
    networks:
      - web

    labels:
      - traefik.main.frontend.rule=Host:drawserver.jonay2000.nl
      - traefik.main.frontend.port=80
      - traefik.main.backend.port=80
      - traefik.api.frontend.rule=Host:api.jonay2000.nl
      - traefik.api.frontend.port=80
      - traefik.api.port=8000
    volumes:
      - ./server/config:/config
      - ./server/logs:/logs
    restart: unless-stopped

networks:
  web:
    external: true
